fix the issue of cursor movement using arrow keys in the search bar for links
deep-foundation/deepcase-app pull request #104
Opened 2023-04-14 20:08 UTC by flakeed

2023-04-16 14:33 UTC, agsagds commented
Associated with https://github.com/deep-foundation/deepcase/issues/102

2023-05-06 18:23 UTC, Konard requested changes

2023-05-06 18:23 UTC, Konard commented on imports/cyto-react-links-card.tsx
> +    }
searchInput should be renamed to activeElement, because it can be not only searchInput

2023-05-06 18:23 UTC, Konard commented on imports/cyto-react-links-card.tsx
> +    }
We not should use activeElement from document.

2026-02-23 03:12 UTC, closed without merging