fix double and more insert of links
deep-foundation/deepcase-app pull request #107
Opened 2023-04-14 22:38 UTC by flakeed

before:
![image](https://user-images.githubusercontent.com/58123600/232166039-501812f8-46f8-4d7c-bc16-d69b4e71c132.png)
after:
![image](https://user-images.githubusercontent.com/58123600/232166096-42567a2e-347a-4d28-84e2-ec628720422f.png)

2023-04-16 14:30 UTC, agsagds commented
Associated with https://github.com/deep-foundation/deepcase/issues/82

2023-05-06 18:45 UTC, Konard requested changes

2023-05-06 18:45 UTC, Konard commented on imports/cyto-react-links-card.tsx
> +
```suggestion

```

2023-05-06 18:45 UTC, Konard commented on imports/cyto-react-links-card.tsx
> +    />
```suggestion
      <SlideFade in={!!selectedLink} offsetX='-0.5rem' style={{position: 'absolute', bottom: 0, right: '-2.8rem'}}>
        <IconButton
          isRound
          variant='solid'
          bg='primary'
          // color='white'
          aria-label='submit button'
          icon={<BsCheck2 />}
          onClick={() => {
            if (isSubmitting) return;
            setIsSubmitting(true);
            if (onSubmit && selectedLink) {
              try {
                await onSubmit(selectedLink);                
              } finally {
                setIsSubmitting(false);
              }
            }
         }}
         isDisabled={isSubmitting}
        />
      </SlideFade>
```

2023-05-06 18:45 UTC, Konard commented on imports/cyto-react-links-card.tsx
> +    />
And add 
```js
const [isSubmitting, setIsSubmitting] = useState(false);
```
somewhere in CytoReactLinksCard before return.

2026-02-23 03:12 UTC, closed without merging