Fixed deep-foundation/deepcase#100
deep-foundation/deepcase-app pull request #109
Opened 2023-04-16 14:17 UTC by agsagds

Replace all "cy" object closures at "cyRef" closures which works correctly.

@Konard You are welcome to review!

2023-06-07 18:30 UTC, Konard requested changes

2023-06-07 18:30 UTC, konard commented on imports/cyto/graph.tsx
> +        />
```suggestion
        />
```

2023-06-07 18:30 UTC, konard commented on imports/cyto/graph.tsx
> +    </div>
```suggestion
    </div>
```

2023-06-08 19:27 UTC, konard approved these changes

2023-06-08 19:27 UTC, merged

2023-06-09 08:55 UTC, FreePhoenix888 commented
@Konard , what about 5000 rubles?

2023-06-09 08:57 UTC, Konard commented
@FreePhoenix888 we wait few days and see how Deep.Case behaves. If nothing else brakes the reward will be paid.

2023-06-28 17:45 UTC, Konard commented
5000 rub reward is paid